### ISSUE TITLE
Unable to run JAFFA from our cluster

### ISSUE THREAD

**Issue by smboyle** [Oshlack/JAFFA#10]
JAFFA currently uses modules, which many clusters do not utilize.  Would you be willing to change this into program paths stated in the config file, as you do for several program requirements?  This would make JAFFA far more accessible to other institutions.

For example, after installing JAFFA and running it on an example data set, i receive the following error.

Pipeline Run:
/JAFFA-version-1.06/tools/bin/bpipe \
run \
/JAFFA-version-1.06/JAFFA_direct.groovy \
/Input_Mod/SampleA_1.fastq.gz Input_Mod/SampleA_2.fastq.gz

Pipeline Output:
========================================= Stage run_check ==========================================
Running JAFFA version 1.06
Checking for required data files...
/Apps/JAFFA-version-1.06/hg19_genCode19.fa
/Apps/JAFFA-version-1.06/hg19_genCode19.tab
/Apps/JAFFA-version-1.06/known_fusions.txt
/genomes/reference/hg19/hg19.fa
/Apps/JAFFA-version-1.06/Masked_hg19.1.bt2
/Apps/JAFFA-version-1.06/hg19_genCode19.1.bt2
All looking good

============================ Stage make_dir_using_fastq_names [SampleA] ============================

================================== Stage prepare_reads [SampleA] ===================================
TrimmomaticPE: Started with arguments: -threads 8 -phred33 /JAFFA_ALK_NPM1_TEST/Input_Mod/SampleA_1.fastq.gz /JAFFA_ALK_NPM1_TEST/Input_Mod/SampleA_2.fastq.gz SampleA/tempp1.fq /dev/null SampleA/tempp2.fq /dev/null LEADING:0 TRAILING:0 MINLEN:35
Input Read Pairs: 56415 Both Surviving: 53692 (95.17%) Forward Only Surviving: 1262 (2.24%) Reverse Only Surviving: 1457 (2.58%) Dropped: 4 (0.01%)
TrimmomaticPE: Completed successfully
53692 reads; of these:
  53692 (100.00%) were paired; of these:
    32284 (60.13%) aligned concordantly 0 times
    21408 (39.87%) aligned concordantly exactly 1 time
    0 (0.00%) aligned concordantly >1 times
39.87% overall alignment rate
32284 reads; of these:
  32284 (100.00%) were paired; of these:
    31721 (98.26%) aligned concordantly 0 times
    563 (1.74%) aligned concordantly exactly 1 time
    0 (0.00%) aligned concordantly >1 times
1.74% overall alignment rate

=================================== Stage get_unmapped [SampleA] ===================================
63442 reads; of these:
  63442 (100.00%) were unpaired; of these:
    17241 (27.18%) aligned 0 times
    46201 (72.82%) aligned exactly 1 time
    0 (0.00%) aligned >1 times
72.82% overall alignment rate
ModuleCmd_Load.c(204):ERROR:105: Unable to locate a modulefile for 'oracle-jdk/1.7_64bit'
ModuleCmd_Load.c(204):ERROR:105: Unable to locate a modulefile for 'pigz'
ModuleCmd_Load.c(204):ERROR:105: Unable to locate a modulefile for 'samtools'
java -ea -Xmx200m -cp /Apps/JAFFA-version-1.06/tools/bbmap/current/ jgi.ReformatReads in=SampleA/unmapped.fastq out=SampleA/temp.fasta threads=8
Exception in thread "main" java.lang.UnsupportedClassVersionError: jgi/ReformatReads : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
Could not find the main class: jgi.ReformatReads. Program will exit.
Cleaned up file SampleA/SampleA_discordant_pairs.bam to .bpipe/trash/SampleA_discordant_pairs.bam
Pipeline failed! (2)

**Comment by datakid** [comment]
There are a number of errors here. Are you still seeing these errors or have you solved it?
