### ISSUE TITLE
which exact GTF/GFF used for the JAFFA Reference Files?

### ISSUE THREAD

**Issue by mdhitch** [Oshlack/JAFFA#101]
Hi, 

Maybe this is clear an obvious and I am missing something, but which exact GTF/GFF files were used for the JAFFA Reference Files? I'm currently using a pipeline for nanopore reads that errors at the JAFFA section, I think it has something to do with the references I am using. I have attempted to use the hg38.fa supplied with the JAFFA reference files as a genome, alas, it seems whichever GTF I use for the pipeline, JAFFA doesn't seem to like it.

Should I not get anywhere with this, my next step is to generate my own reference set. 

Many thanks in advance,

Matt

**Comment by nadiadavidson** [comment]
Hi Matt,

JAFFA doesn't use any .gft/.gff files, instead it uses a couple of other files formats to get information about the reference annotation. These files are packaged up in the reference tar ball you can download at https://github.com/Oshlack/JAFFA/wiki/Download

If you've tried to use this and getting an error, please feel free to post the error and other details (see https://github.com/Oshlack/JAFFA/wiki/FAQandTroubleshooting#other-errors for information that's useful for us). Are you running the RNA-Seq analysis pipeline developed by ONT? It may be that some of the files are incompatible, but we could reach out to them as well if this is the case.

Cheers,
Nadia.

**Comment by mdhitch** [comment]
Thanks for the reply Nadia. It seems I had a RAM issue which looks like it may be solved.

Many thanks for your help.

Matt
