### ISSUE TITLE
Bpipe error groovy.lang.MissingMethodException: No signature of method: bpipe.Branch.plus() is applicable for argument types: (String) values: [.fasta]

### ISSUE THREAD

**Issue by wdesaintjean** [Oshlack/JAFFA#102]
Hi,

I use a docker image (build from the jaffa github Dockerfile) to run Jaffal on long reads in a nextflow pipeline, with this command:

`bpipe run -p refBase=$jaffal_ref_dir -p genome=mm10 -p annotation=genCodeVM4 /opt/JAFFA/JAFFAL.groovy $fastq`

But this error occur every time:
`=========================================== Bpipe Error ============================================
  
  An error occurred executing your pipeline:
  
  No signature of method: bpipe.Branch.plus() is applicable for argument types: (String) values: [.fasta]
  Possible solutions: is(java.lang.Object), split(groovy.lang.Closure), use([Ljava.lang.Object;), wait(), size(), dump()
  
  
  Please see the details below for more information.
  
  ========================================== Error Details ===========================================
  
  groovy.lang.MissingMethodException: No signature of method: bpipe.Branch.plus() is applicable for argument types: (String) values: [.fasta]
  Possible solutions: is(java.lang.Object), split(groovy.lang.Closure), use([Ljava.lang.Object;), wait(), size(), dump()
  	at JAFFAL.groovy$_run_closure1.doCall(JAFFAL.groovy:19)
  	at bpipe.PipelineStage.runWrappedBody(PipelineStage.groovy:459)
  	at bpipe.PipelineStage.runBody(PipelineStage.groovy:432)
  	at bpipe.PipelineStage.run(PipelineStage.groovy:226)
  	at bpipe.PipelineCategory$_plus_closure5.doCall(PipelineCategory.groovy:236)
  	at bpipe.PipelineCategory$_plus_closure5.call(PipelineCategory.groovy)
  	at bpipe.PipelineStage.runWrappedBody(PipelineStage.groovy:459)
  	at bpipe.PipelineStage.runBody(PipelineStage.groovy:432)
  	at bpipe.PipelineStage.run(PipelineStage.groovy:226)
  	at bpipe.PipelineStage$run.call(Unknown Source)
  	at bpipe.Pipeline.runSegment(Pipeline.groovy:683)
  	at bpipe.BranchRunner.run(BranchRunner.groovy:69)
  
  
  ====================================================================================================
  
  More details about why this error occurred may be available in the full log file .bpipe/bpipe.log`

This error occur with my data and the test data of the git repository, I tried to change the parameter `fastqInputFormat`, but it doesn't seem to be the root of the problem.

**Comment by wdesaintjean** [comment]
In the bpipe logs, it seem the .fastq.gz is not convert in fasta, for an unknown reason, and the program try to use strange name like `new default output = ONT-fus-sim_75err.fastq/ONT-fus-sim_75err.fastq.gz.get_fasta`.

Extract of the logs:

bpipe.Concurrency       [1]     INFO    |3:10:39 Register resource requestor bpipe.Pipeline@373f7450 
bpipe.Concurrency       [1]     INFO    |3:10:39 Waiting for 1 parallel stages to complete (pool.active=1 pool.tasks=1) 
bpipe.PipelineContext   [28]    INFO    |3:10:39 Setting output [ONT-fus-sim_75err.fastq.gz] on context 374533960 in thread 28 
bpipe.PipelineContext   [28]    INFO    |3:10:39 Actual output set: [ONT-fus-sim_75err.fastq.gz] 
bpipe.Pipeline  [28]    INFO    |3:10:39 Created dummy prior stage for thread 28 with outputs : [ONT-fus-sim_75err.fastq.gz] 
bpipe.Pipeline  [28]    INFO    |3:10:39 Running segment with inputs [ONT-fus-sim_75err.fastq.gz] 
bpipe.Dependencies      [28]    INFO    |3:10:39 Checking 1 input (s)  
bpipe.PipelineDelegate  [28]    INFO    |3:10:39 Setting or creating a delegate for context 1132233399 body 333879495/java.lang.Class in thre
ad 28 
bpipe.PipelineDelegate  [28]    INFO    |3:10:39 Created new delegate bpipe.PipelineDelegate@29552bcc overriding type java.lang.Class in thre
ad 28 
bpipe.Dependencies      [28]    INFO    |3:10:39 Checking 1 input (s)  
bpipe.PipelineStage     [28]    INFO    |3:10:39 Stage get_fasta (ONT-fus-sim_75err) : INPUT=[ONT-fus-sim_75err.fastq.gz] OUTPUT=ONT-fus-sim_
75err.fastq.gz.get_fasta 
bpipe.PipelineDelegate  [28]    INFO    |3:10:39 Setting or creating a delegate for context 1977176897 body 1710191146/script1705590637428311
990101 in thread 28 
bpipe.PipelineDelegate  [28]    INFO    |3:10:39 Created new delegate bpipe.PipelineDelegate@75d21d7d overriding type script17055906374283119
90101 in thread 28 
bpipe.PipelineContext   [28]    INFO    |3:10:39 No inputs resolved by input wrappers: outputs will be based on default ONT-fus-sim_75err.fas
tq.gz.get_fasta 
bpipe.OutputDirectoryWatcher    [20]    INFO    |3:10:39 File ONT-fus-sim_75err.fastq was created in directory . 
bpipe.OutputDirectoryWatcher    [28]    INFO    |3:10:39 Creating directory watcher for ONT-fus-sim_75err.fastq 
bpipe.PipelineContext   [28]    INFO    |3:10:39 Output set to ONT-fus-sim_75err.fastq (new default output = ONT-fus-sim_75err.fastq/ONT-fus-
sim_75err.fastq.gz.get_fasta) 
bpipe.PipelineStage     [28]    SEVERE  |3:10:39 Cleaning up outputs due to error: groovy.lang.MissingMethodException: No signature of method
: bpipe.Branch.plus() is applicable for argument types: (String) values: [.fasta]
Possible solutions: is(java.lang.Object), split(groovy.lang.Closure), use([Ljava.lang.Object;), wait(), size(), dump() 
bpipe.OutputDirectoryWatcher    [29]    INFO    |3:10:39 Watching directories using native watcher 
bpipe.PipelineStage     [28]    SEVERE  |3:10:39 Cleaning up outputs due to error: groovy.lang.MissingMethodException: No signature of method
: bpipe.Branch.plus() is applicable for argument types: (String) values: [.fasta]
Possible solutions: is(java.lang.Object), split(groovy.lang.Closure), use([Ljava.lang.Object;), wait(), size(), dump() 
bpipe.Pipeline  [28]    INFO    |3:10:39 Finished running segment in thread 28 for inputs [ONT-fus-sim_75err.fastq.gz] 
bpipe.OutputDirectoryWatcher    [29]    INFO    |3:10:39 Using high sensitivity file watcher for ONT-fus-sim_75err.fastq 

Could you help me, please?
Many thanks,
William

**Comment by agata-sm** [comment]
@wdesaintjean I have encountered similar error (not identical) when using my own JAFFAL container (built using Dockerfile from this repository). I could identify the source of the problem to bpipe version (the pipeline runs ok using an older bpipe version). However, down the line you'll encounter a different issue: you need to include a call to compile `make_3_gene_fusion_table` which is not included in this Dockerfile. If you want to check my modifications go to (https://github.com/agata-sm/JAFFA/blob/main/docker/Dockerfile) however please be aware I have slightly modified JAFFAL (see my problem with base quality encoding three issues back), and my file installs JAFFAL from my fork - so if you want to use it, change the relevant repo path.

**Comment by nadiadavidson** [comment]
Thanks for these suggestions @agata-sm. I will try to fix the Dockerfile following your fixes! Although I'm not so experienced with Docker, so happy to receive pull requests to the repository.

Apologies for not responding to your earlier issue. I will reply now, for the record, although realise you've already gotten around it.

**Comment by wdesaintjean** [comment]
It's working !!!! Thank you very much, @agata-sm.
I used the parts of your image where you install the older version of bpipe, and the line
`RUN g++ -std=c++11 -O3 -o JAFFA/tools/bin/make_3_gene_fusion_table JAFFA/src/make_3_gene_fusion_table.c++`
it's working with the original repo of JAFFA.

However, I met another error, that seems the same than the issue 90
https://github.com/Oshlack/JAFFA/issues/90

Did you have this problem in your version of the image, @agata-sm?

I can't really ignore the error, like said in the issue, because this will stop the pipeline where I use Jaffal

Thank you for your help.
William

**Comment by agata-sm** [comment]
@wdesaintjean Yes, I saw the "permission denied" error when trying to execute `make_3_gene_fusion_table`. It was because it was not compiled when using the original Docker image. If you compile it, and it still does not seem to be found, then perhaps you need to also modify `tools.groovy` - just add a line with its name, such as it is done for other tools. I did it _just in case_ and my Docker image supports JAFFAL run until completion. I am not sure you need to create a new container, I'd edit `tools.groovy` in your local JAFFAL installation and give it a go.

**Comment by agata-sm** [comment]
@nadiadavidson I'll create a PR with my mods to the Dockerfile. Seems also that `tools.groovy` needs to be amended.

**Comment by wdesaintjean** [comment]
Add make_3_gene_fusion_table to tools.groovy was the solution. Once more, many thanks, @agata-sm.

Have a good day
William

**Comment by nadiadavidson** [comment]
> @nadiadavidson I'll create a PR with my mods to the Dockerfile. Seems also that `tools.groovy` needs to be amended.

That we be wonderful, Thanks!

**Comment by Sanat-Mishra** [comment]
I'm still facing the same issue - running on HPC, without docker/singularity use. I've also updated tool.groovy.

**Comment by Sanat-Mishra** [comment]
Hey guys, I fixed this issue.
Turns out, the fix is modifying lines 167 through 170 in the JAFFA_stages.groovy file. The command should be 
```
....
 else if (inputs.size() == 2) {  // paired reads
        produce(branch.name+"_filtered_reads.fastq.1.gz",
                branch.name+"_filtered_reads.fastq.2.gz",
                branch.name+"_leftover_reads.fastq.1.gz",
                branch.name+"_leftover_reads.fastq.2.gz")
....
```

instead of using just 'branch'.

**Comment by Sanat-Mishra** [comment]
> Hey guys, I fixed this issue. Turns out, the fix is modifying lines 167 through 170 in the JAFFA_stages.groovy file. The command should be
> 
> ```
> ....
>  else if (inputs.size() == 2) {  // paired reads
>         produce(branch.name+"_filtered_reads.fastq.1.gz",
>                 branch.name+"_filtered_reads.fastq.2.gz",
>                 branch.name+"_leftover_reads.fastq.1.gz",
>                 branch.name+"_leftover_reads.fastq.2.gz")
> ....
> ```
> 
> instead of using just 'branch'.

This will have to be fixed throughout the JAFFA_stages.groovy file.
