### ISSUE TITLE
unable download jaffa reference data in china 

### ISSUE THREAD

**Issue by komais** [Oshlack/JAFFA#11]
hi, i think jaffa is a wonderful tools for fusion detect, so i downloaded software and use it in my study. But i met a problem when i downloaded JAFFA_REFERENCE_FILES_HG19_GENCODE19.tar.gz in china because of Great fire wall in china.  
so how could i download JAFFA_REFERENCE_FILES_HG19_GENCODE19.tar.gz in china ? my google mail address is  liutao.lotus@gmail.com , could you share this file through my google driver? 
Thank you very much

**Comment by datakid** [comment]
did you get the hg19 files you needed? Let me know. datakid@gmail.com

**Comment by flyman0302** [comment]
hi, I also come from China, and also cannot download the reference files.  How can I get these files?

**Comment by nadiadavidson** [comment]
Hi, do you know of a file sharing service which would work for China? I'm happy to put files wherever. The other option would be to generate these files yourself following the instructions on https://github.com/Oshlack/JAFFA/wiki/FAQandTroubleshooting#how-can-i-generate-the-reference-files-for-a-non-supported-genome I'm happy to guide you through it.

**Comment by flyman0302** [comment]
Dear Dr. Oshlack,

Thank you very much for your kindly reply. Many file sharing services work for China, like http://c-t.yunpan.360.cn/. But they used chinese language. Maybe you can put your files in other file sharing service except google drive. However, I will follow these instructions to generate these files myself.  Thanks again.

Best regards,
Zhong-Xi Huang PhD
Institute of Cancer Research
Southern Medical University

**Comment by flyman0302** [comment]
Thank you very much! I have get it.
