### ISSUE TITLE
Output file name?

### ISSUE THREAD

**Issue by datakid** [Oshlack/JAFFA#15]
Is it possible to change the output file name by using 

`'-p outputName="andNowForSomethingCompletelyDifferent_results" '`

for instance?

**Comment by nadiadavidson** [comment]
That should work. Have you tried?

**Comment by datakid** [comment]
No! I'm just the sys admin, I'll ask Dr Christie.

**Comment by datakid** [comment]
This works - I think it's worth putting in the documentation somewhere.
