### ISSUE TITLE
bash: line 1: PE: command not found Pipeline failed! (2) 

### ISSUE THREAD

**Issue by deepbiomed9** [Oshlack/JAFFA#21]
Hi,
I am running JAFFA for the first time. I think i have installed everything correctly.
I am getting an error at "Stage prepare_reads" (commandlog.txt attached)

bash: line 1: PE: command not found
Pipeline failed! (2) 

Command failed with exit status = 127 : 

PE -threads 1 -phred33 /media/sf_John_SERVER/JAFFA/JAFFA-version-1.07/test/CR004_S24_L005_R1_001.fastq.gz /media/sf_John_SERVER/JAFFA/JAFFA-version-1.07/test/CR004_S24_L005_R2_001.fastq.gz  CR004_S24_L005/tempp1.fq /dev/null CR004_S24_L005/tempp2.fq /dev/null  LEADING:0 TRAILING:0 MINLEN:35 ;  function fix_ids {  cat $1 | awk -v app=$2                                 'BEGIN{ i=0 }{                                    if(i==0) printf("%s\/%s\n", $1, app) ;                                    else print $1 ;                                    i++ ;                                    if(i==4) i=0 }' 2>/dev/null                ; } ; 	      fix_ids CR004_S24_L005/tempp1.fq 1 > CR004_S24_L005/CR004_S24_L005_trim1.fastq ; 	      fix_ids CR004_S24_L005/tempp2.fq 2 > CR004_S24_L005/CR004_S24_L005_trim2.fastq ;               rm CR004_S24_L005/tempp1.fq CR004_S24_L005/tempp2.fq ;                -k1 --no-mixed --no-discordant --mm --very-fast  	         --al-conc-gz CR004_S24_L005/CR004_S24_L005_filtered_reads.fastq.gz --un-conc CR004_S24_L005/temp_trans_unmap_reads.fastq  	       	 -p 1 -x /media/sf_John_SERVER/JAFFA/JAFFA-version-1.07/hg38_genCode22  	       	 -1 CR004_S24_L005/CR004_S24_L005_trim1.fastq -2 CR004_S24_L005/CR004_S24_L005_trim2.fastq -S /dev/null ; 	       -k1 --no-mixed --no-discordant --mm --very-fast --un-conc-gz CR004_S24_L005/CR004_S24_L005_leftover_reads.fastq.gz -p 1 -x /media/sf_John_SERVER/JAFFA/JAFFA-version-1.07/Masked_hg38                 	 -1 CR004_S24_L005/temp_trans_unmap_reads.1.fastq -2 CR004_S24_L005/temp_trans_unmap_reads.2.fastq -S /dev/null ; 	      cat CR004_S24_L005/CR004_S24_L005_leftover_reads.fastq.1.gz >> CR004_S24_L005/CR004_S24_L005_filtered_reads.fastq.1.gz ; 	      cat CR004_S24_L005/CR004_S24_L005_leftover_reads.fastq.2.gz >> CR004_S24_L005/CR004_S24_L005_filtered_reads.fastq.2.gz ; 	      rm CR004_S24_L005/temp_trans_unmap_reads.1.fastq CR004_S24_L005/temp_trans_unmap_reads.2.fastq 	         CR004_S24_L005/CR004_S24_L005_trim1.fastq CR004_S24_L005/CR004_S24_L005_trim2.fastq ;

Pipeline failed! (2) 

One or more parallel stages aborted. The following messages were reported: 

Command failed with exit status = 127 : 

PE -threads 1 -phred33 /media/sf_John_SERVER/JAFFA/JAFFA-version-1.07/test/CR004_S24_L005_R1_001.fastq.gz /media/sf_John_SERVER/JAFFA/JAFFA-version-1.07/test/CR004_S24_L005_R2_001.fastq.gz  CR004_S24_L005/tempp1.fq /dev/null CR004_S24_L005/tempp2.fq /dev/null  LEADING:0 TRAILING:0 MINLEN:35 ;  function fix_ids {  cat $1 | awk -v app=$2                                 'BEGIN{ i=0 }{                                    if(i==0) printf("%s\/%s\n", $1, app) ;                                    else print $1 ;                                    i++ ;                                    if(i==4) i=0 }' 2>/dev/null                ; } ; 	      fix_ids CR004_S24_L005/tempp1.fq 1 > CR004_S24_L005/CR004_S24_L005_trim1.fastq ; 	      fix_ids CR004_S24_L005/tempp2.fq 2 > CR004_S24_L005/CR004_S24_L005_trim2.fastq ;               rm CR004_S24_L005/tempp1.fq CR004_S24_L005/tempp2.fq ;                -k1 --no-mixed --no-discordant --mm --very-fast  	         --al-conc-gz CR004_S24_L005/CR004_S24_L005_filtered_reads.fastq.gz --un-conc CR004_S24_L005/temp_trans_unmap_reads.fastq  	       	 -p 1 -x /media/sf_John_SERVER/JAFFA/JAFFA-version-1.07/hg38_genCode22  	       	 -1 CR004_S24_L005/CR004_S24_L005_trim1.fastq -2 CR004_S24_L005/CR004_S24_L005_trim2.fastq -S /dev/null ; 	       -k1 --no-mixed --no-discordant --mm --very-fast --un-conc-gz CR004_S24_L005/CR004_S24_L005_leftover_reads.fastq.gz -p 1 -x /media/sf_John_SERVER/JAFFA/JAFFA-version-1.07/Masked_hg38                 	 -1 CR004_S24_L005/temp_trans_unmap_reads.1.fastq -2 CR004_S24_L005/temp_trans_unmap_reads.2.fastq -S /dev/null ; 	      cat CR004_S24_L005/CR004_S24_L005_leftover_reads.fastq.1.gz >> CR004_S24_L005/CR004_S24_L005_filtered_reads.fastq.1.gz ; 	      cat CR004_S24_L005/CR004_S24_L005_leftover_reads.fastq.2.gz >> CR004_S24_L005/CR004_S24_L005_filtered_reads.fastq.2.gz ; 	      rm CR004_S24_L005/temp_trans_unmap_reads.1.fastq CR004_S24_L005/temp_trans_unmap_reads.2.fastq 	         CR004_S24_L005/CR004_S24_L005_trim1.fastq CR004_S24_L005/CR004_S24_L005_trim2.fastq ;

======================================== Pipeline Finished =========================================
[commandlog.txt](https://github.com/Oshlack/JAFFA/files/574402/commandlog.txt)

**Comment by deepbiomed9** [comment]
Solved

in tools.groovy most of the tools paths were empty

**Comment by nadiadavidson** [comment]
Once you got the tools installed did it work?
