### ISSUE TITLE
JAFFA run halted

### ISSUE THREAD

**Issue by bharatimehani** [Oshlack/JAFFA#25]
I am getting following error and do not know how to solve this.
Anyone has any idea regarding this type of error.
after running
> #filter out all transcripts which are only covered by one reference transcript

I got this error:

**> candidates=do.call("rbind",lapply(split_results,multi_gene))
[1] 10
"Error: Please use 'drop.self' and/or 'drop.redundant' instead of the
  'ignoreSelf' and/or 'ignoreRedundant' arguments."
Execution halted

**Comment by nadiadavidson** [comment]
Hello,

Thanks for reporting this. The error is a result of function arguments becoming redundant in the latest R. You can fix it by replacing the file, process_transcriptome_blat_table.R, with the one at 
https://github.com/Oshlack/JAFFA/blob/master/process_transcriptome_blat_table.R

This fix will go into the next release of JAFFA.

Cheers,
Nadia.

**Comment by bow** [comment]
Hi @nadiadavidson,

I hope you don't mind me commenting on this issue again, but I just stumbled on an error on the same line and I thought it may be related with this issue.

Here's my error message:
```
Error in do.call("rbind", lapply(split_results, multi_gene)) : 
  error in evaluating the argument 'args' in selecting a method for function 'do.call': Error in .local(query, subject, maxgap, minoverlap, type, select, algorithm,  : 
  unused arguments (drop.self = TRUE, drop.redundant = TRUE)
Calls: lapply ... findOverlaps -> .local -> findOverlaps -> findOverlaps -> .local
Execution halted
```
I'm using Jaffa 1.09 (installed from [bioconda](https://bioconda.github.io/recipes/jaffa/README.html)) and my R version is `3.2.2 (2015-08-14) -- "Fire Safety"`.

Do you have any pointers on what may have caused this?

**Comment by Sigmatilde** [comment]
Hi @nadiadavidson 

I have the same error of @bow .
Do you have any idea to how to fix that?

Thanks
