### ISSUE TITLE
JAFFA Pipeline failed at creation of jaffa_results-file

### ISSUE THREAD

**Issue by zibiz** [Oshlack/JAFFA#26]
Hi,

I'm learning to use JAFFA by using the example Demo-files. Installation went without problems. I'm trying to use the direct mode, it goes smoothly all the way to "Stage compile_all_results", but for some reason I'll get an error before the result file is created, leaving me with jaffa_results.temp with 19 rows and 4 columns. The summary files in both samples folders look complete. My last terminal log:

R version 3.2.3 (2015-12-10) -- "Wooden Christmas-Tree"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)
R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.
  Natural language support but running in an English locale
R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.
Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.
> options(echo=F)
Compiling the results from:
BT474-demo MCF7-demo
Done writing output jaffa_results.csv
Cleaned up file jaffa_results.fasta to .bpipe/trash/jaffa_results.fasta.5
Cleaned up file jaffa_results.csv to .bpipe/trash/jaffa_results.csv.5
ERROR: Command failed with exit status = 1 : 

/usr/bin/R --vanilla --args jaffa_results /home/zibi/BT474-demo/BT474-demo.summary /home/zibi/MCF7-demo/MCF7-demo.summary < /home/zibi/JAF/compile_results.R ; function get_sequence {  	     if [ $1 == "sample" ] ; then return ; fi ;      fusions_file=$1/$1.fusions.fa ; 	     new_id=$1---$2---$3 ;              echo ">$new_id" >> jaffa_results.fasta ; 	     break=$4 ;  	     sequence=`grep -A1 "^>$3" $fusions_file | grep -v "^>"` ; 	     start=`echo $sequence | cut -c 1-$((${break}-1))` ; 	     middle=`echo $sequence | cut -c $break-$((${break}+1)) | tr '[:upper:]' '[:lower:]'` ; 	     string_length=`echo ${#sequence}` ; 	     end=`echo $sequence | cut -c $(($break+2))-$string_length ` ; 	     echo $start$middle$end >> jaffa_results.fasta ; 	     `# grep $3 $1/$1_genome.psl >> jaffa_results.psl ;` ; 	  } ; 	  rm -f jaffa_results.fasta ; 	  cat jaffa_results.temp | while read line ; do get_sequence $line ; done ; 	  rm jaffa_results.temp ; 	  echo "Done writing jaffa_results.fasta" ; 	  echo "All Done" 

I'm running Linux Ubuntu 16.04.2 LTS 64bit using Oracle VM VirtualBox with Intel Core i7-6700 CPU (4x3,4Ghz) and 11Gb dedicated RAM.  

Hope I provided you with enough details, and thank you in advance!

**Comment by zibiz** [comment]
assembly-mode seems working just fine, producing results in .csv and .fa formats without errors. Hybrid mode results in same error as mentioned above.

**Comment by kunstner** [comment]
Same error here and no final files created.

I am able to run the command directly after the crash on the data and I retrieve the final output files.

**Comment by nadiadavidson** [comment]
What system and version of JAFFA and R are you running?

Cheers,
Nadia.

**Comment by kunstner** [comment]
I'm running JAFFA 1.08 using the direct mode (with R 3.3.3) on a Debian 8.7 system. 

Best,
 Axel
