### ISSUE TITLE
JAFFA's license / Bioconda package

### ISSUE THREAD

**Issue by holtgrewe** [Oshlack/JAFFA#28]
Hi, I'd like to package JAFFA into Bioconda (see bioconda/bioconda-recipes#4132). The main advantage is that all dependencies can be installed automatically.

For this, I'd need the license of JAFFA (e.g., BSD, MIT, GPL, free for academic use and Bioconda can redistribute).

**Comment by nadiadavidson** [comment]
Hi, JAFFA should be under the GPL. I'll add the license info to github now.

**Comment by holtgrewe** [comment]
Thanks!
