### ISSUE TITLE
error in get_final_list

### ISSUE THREAD

**Issue by amywebb** [Oshlack/JAFFA#30]
I'm running JAFFA 1.08 with hg38_gencode20, java version 1.8.0_121, R version 3.3.2.

I had to update my process_transcriptome_blat_table.R to fix the 'ignoreSelf'/'ignoreRedundant' error

But I'm having an error at stage get_final_list and it sounds like the list is empty.  I'm running on the BT474 demo using command /users/PAS1208/osu0972/awebb/bin/JAFFA/JAFFA-version-1.08/tools/bin/bpipe run /users/PAS1208/osu0972/awebb/bin/JAFFA/JAFFA-version-1.08/JAFFA_direct.groovy /users/PAS1208/osu0972/awebb/bin/JAFFA/JAFFA-version-1.08/BT474/*

My BT474-demo.psl file has 2441 lines in it.

My error is as follows:
Error in read.table(file = file, header = header, sep = sep, quote = quote,  :
  no lines available in input
Calls: read.delim -> read.table
Execution halted
ERROR: Command failed with exit status = 1 :

/usr/local/R/3.3.2/bin/R --vanilla --args BT474-demo/BT474-demo_genome.psl BT474-demo/BT474-demo.reads /users/PAS1208/osu0972/awebb/bin/JAFFA/JAFFA-version-1.08/hg38_genCode20.tab /users/PAS1208/osu0972/awebb/bin/JAFFA/JAFFA-version-1.08/known_fusions.txt 10000 NoSupport,PotentialRegularTranscript BT474-demo/BT474-demo.summary < /users/PAS1208/osu0972/awebb/bin/JAFFA/JAFFA-version-1.08/make_final_table.R

And the entire run history is as follows:
=================================
|                              Starting Pipeline at 2017-03-28 13:28                               |
=================================

========================================= Stage run_check 
========================== Stage make_dir_using_fastq_names (BT474-demo) 
================================= Stage prepare_reads (BT474-demo) 
TrimmomaticPE: Started with arguments: -threads 1 -phred33 /users/PAS1208/osu0972/awebb/bin/JAFFA/JAFFA-version-1.08/BT474/BT474-demo_1.fastq.gz /users/PAS1208/osu0972/awebb/bin/JAFFA/JAFFA-version-1.08/BT474/BT474-demo_2.fastq.gz BT474-demo/tempp1.fq /dev/null BT474-demo/tempp2.fq /dev/null LEADING:0 TRAILING:0 MINLEN:35
Input Read Pairs: 83014 Both Surviving: 83014 (100.00%) Forward Only Surviving: 0 (0.00%) Reverse Only Surviving: 0 (0.00%) Dropped: 0 (0.00%)
TrimmomaticPE: Completed successfully
83014 reads; of these:
  83014 (100.00%) were paired; of these:
    1325 (1.60%) aligned concordantly 0 times
    81689 (98.40%) aligned concordantly exactly 1 time
    0 (0.00%) aligned concordantly >1 times
98.40% overall alignment rate
1325 reads; of these:
  1325 (100.00%) were paired; of these:
    1174 (88.60%) aligned concordantly 0 times
    151 (11.40%) aligned concordantly exactly 1 time
    0 (0.00%) aligned concordantly >1 times
11.40% overall alignment rate

================================= Stage get_unmapped (BT474-demo) 
2348 reads; of these:
  2348 (100.00%) were unpaired; of these:
    719 (30.62%) aligned 0 times
    1629 (69.38%) aligned exactly 1 time
    0 (0.00%) aligned >1 times
69.38% overall alignment rate
java -ea -Xmx200m -cp /users/PAS1208/osu0972/awebb/bin/JAFFA/JAFFA-version-1.08/tools/bbmap/current/ jgi.ReformatReads in=BT474-demo/unmapped.fastq out=BT474-demo/temp.fasta threads=1
Executing jgi.ReformatReads [in=BT474-demo/unmapped.fastq, out=BT474-demo/temp.fasta, threads=1]
Set threads to 1
Changed from ASCII-33 to ASCII-64 on input quality 92 for base T while prescanning.
Input is being processed as unpaired
Input:                          719 reads               54644 bases
Output:                         719 reads (100.00%)     54644 bases (100.00%)
Time:                           0.142 seconds.
Reads Processed:         719    5.05k reads/sec
Bases Processed:       54644    0.38m bases/sec
java -Djava.library.path=/users/PAS1208/osu0972/awebb/bin/JAFFA/JAFFA-version-1.08/tools/bbmap/jni/ -ea -Xmx48285m -Xms48285m -cp /users/PAS1208/osu0972/awebb/bin/JAFFA/JAFFA-version-1.08/tools/bbmap/current/ jgi.Dedupe in=BT474-demo/temp.fasta out=BT474-demo/BT474-demo.fasta threads=1 absorbcontainment=f
Executing jgi.Dedupe [in=BT474-demo/temp.fasta, out=BT474-demo/BT474-demo.fasta, threads=1, absorbcontainment=f]
Set threads to 1
Initial:
Memory: max=48522m, free=47762m, used=760m
Found 210 duplicates.
Finished exact matches.    Time: 0.126 seconds.
Memory: max=48522m, free=45990m, used=2532m
Input:                          719 reads               54644 bases.
Duplicates:                     210 reads (29.21%)      15960 bases (29.21%)            0 collisions.
Result:                         509 reads (70.79%)      38684 bases (70.79%)
Printed output.            Time: 0.057 seconds.
Memory: max=48522m, free=45737m, used=2785m
Time:                           0.189 seconds.
Reads Processed:         719    3.81k reads/sec
Bases Processed:       54644    0.29m bases/sec

=========================== Stage align_reads_to_annotation (BT474-demo) 
Using tileSize of 15
Loaded 287210946 letters in 188801 sequences
Searched 38684 bases in 509 sequences
real    0m5.419s
user    0m4.871s
sys     0m0.362s

============================== Stage filter_transcripts (BT474-demo) ===============================
real    0m19.167s
user    0m17.614s
sys     0m0.341s

=========================== Stage extract_fusion_sequences (BT474-demo) 
java -ea -Xmx200m -cp /users/PAS1208/osu0972/awebb/bin/JAFFA/JAFFA-version-1.08/tools/bbmap/current/ jgi.ReformatReads in=BT474-demo/BT474-demo.fasta out=stdout.fasta fastawrap=0
Executing jgi.ReformatReads [in=BT474-demo/BT474-demo.fasta, out=stdout.fasta, fastawrap=0]
Input is being processed as unpaired
Input:                          509 reads               38684 bases
Output:                         509 reads (100.00%)     38684 bases (100.00%)
Time:                           0.151 seconds.
Reads Processed:         509    3.37k reads/sec
Bases Processed:       38684    0.26m bases/sec

========================== Stage align_transcripts_to_genome (BT474-demo) 
============================ Stage make_simple_reads_table (BT474-demo) 
R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)
R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.
  Natural language support but running in an English locale
R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.
Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.
> #options(echo=FALSE)
>
> options(stringsAsFactors=F)
>
> args = commandArgs(trailingOnly = TRUE)
>
> ## load the table of candidates
> candidates=read.delim(args[1],header=F)
>
> ## load the reference annotation which maps gene IDs to
> ref=read.delim(args[2],stringsAsFactors=F)[,c("name","name2")]
>
> ## load the actually gene ids as they are stored in the bam file
> ref_contigs=read.delim(args[3],header=F,stringsAsFactors=F)[,1]
>
> ## replace the contig ids in the ref table
> names(ref_contigs)<-sapply(strsplit(ref_contigs,"_"),function(x){x[3]})
> ref$name<-ref_contigs[ref$name]
> sref=split(ref$name,ref$name2)
> sref=sapply(sref,function(x){paste(x,collapse=" ")})
>
>
> #now make the table which need to be run on the .bam file
> genes=unique(candidates$V4)
> sgenes=lapply(strsplit(genes,":"),function(x){sort(x)})
> sgenes=unique(sgenes)
> g1=sapply(sgenes,function(x){ sref[[x[1]]]  })
> g2=sapply(sgenes,function(x){ sref[[x[2]]]  })
> genes_new=sapply(sgenes,function(x){ paste(x[1],x[2],sep=":") })
> write.table(data.frame(genes_new,g1,g2),args[4],sep="?",row.names=F,col.names=F,quote=F)
>
R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)
R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.
  Natural language support but running in an English locale
R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.
Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.
> #options(echo=FALSE)
>
> options(stringsAsFactors=F)
> args = commandArgs(trailingOnly = TRUE)
>
> ## load the table of candidates
> candidates=read.delim(args[1],header=F)
>
> ## fix the ids to be alphabetically ordered
> candidates$V4=sapply(strsplit(candidates$V4,":"),function(x){ paste(sort(x),collapse=":") })
> colnames(candidates)<-c("transcript","break_min","break_max","fusion_genes","length")
> candidates$length<-NULL
> candidates$spanning_pairs<-0
> candidates$spanning_reads<-1
>
> ## load the count data
> sr=read.delim(args[2],header=F)
>
> for( n in 1:length(sr[,1])){
+    entries=candidates$fusion_genes==sr[n,1]
+    spanning_rs=sr[n,2]
+    if(spanning_rs>0){ #distribute evelyn amongst instances of this fusion in the list
+       scounts=table(rep_len(1:sum(entries),spanning_rs))
+       if(length(scounts)<sum(entries))
+          scounts=c(scounts,rep(0,sum(entries)-length(scounts)))
+       candidates$spanning_pairs[entries]<-scounts
+    }
+ }
>
> write.table(candidates,args[3],sep="\t",row.names=F,col.names=T,quote=F)
>

================================ Stage get_final_list (BT474-demo) 
R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)
R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.
  Natural language support but running in an English locale
R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.
Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.
> options(echo=FALSE)
Error in read.table(file = file, header = header, sep = sep, quote = quote,  :
  no lines available in input
Calls: read.delim -> read.table
Execution halted
ERROR: Command failed with exit status = 1 :

/usr/local/R/3.3.2/bin/R --vanilla --args BT474-demo/BT474-demo_genome.psl BT474-demo/BT474-demo.reads /users/PAS1208/osu0972/awebb/bin/JAFFA/JAFFA-version-1.08/hg38_genCode20.tab /users/PAS1208/osu0972/awebb/bin/JAFFA/JAFFA-version-1.08/known_fusions.txt 10000 NoSupport,PotentialRegularTranscript BT474-demo/BT474-demo.summary < /users/PAS1208/osu0972/awebb/bin/JAFFA/JAFFA-version-1.08/make_final_table.R

========================================= Pipeline Failed 

One or more parallel stages aborted. The following messages were reported:

Branch BT474-demo in stage Unknown reported message:

Command failed with exit status = 1 :

/usr/local/R/3.3.2/bin/R --vanilla --args BT474-demo/BT474-demo_genome.psl BT474-demo/BT474-demo.reads /users/PAS1208/osu0972/awebb/bin/JAFFA/JAFFA-version-1.08/hg38_genCode20.tab /users/PAS1208/osu0972/awebb/bin/JAFFA/JAFFA-version-1.08/known_fusions.txt 10000 NoSupport,PotentialRegularTranscript BT474-demo/BT474-demo.summary < /users/PAS1208/osu0972/awebb/bin/JAFFA/JAFFA-version-1.08/make_final_table.R

Use 'bpipe errors' to see output from failed commands.

**Comment by leiendeckerlu** [comment]
I encounter the same error...

**Comment by nadiadavidson** [comment]
Hello,
Do you mind posting the result of "ls -l" in the directory BT474-demo/ and also the directory where you installed JAFFA? It sounds like the result of some earlier stages might be empty.
Cheers,
Nadia.

**Comment by leiendeckerlu** [comment]
Hi,
yeah for sure, here we go:
```
-rwxrwx--- 1 user group.GRP 6.8M May 22 10:40 BT474-demo_discordant_pairs.bam
-rwxrwx--- 1 user group.GRP 1.6M May 22 10:40 BT474-demo_discordant_pairs.bam.bai
-rwxrwx--- 1 user group.GRP  44K May 22 10:40 BT474-demo.fasta
-rwxrwx--- 1 user group.GRP 5.6M May 22 10:40 BT474-demo_filtered_reads.fastq.1.gz
-rwxrwx--- 1 user group.GRP 5.7M May 22 10:40 BT474-demo_filtered_reads.fastq.2.gz
-rwxrwx--- 1 user group.GRP    0 May 22 10:40 BT474-demo.ignore
-rwxrwx--- 1 user group.GRP  68K May 22 10:40 BT474-demo_leftover_reads.fastq.1.gz
-rwxrwx--- 1 user group.GRP  70K May 22 10:40 BT474-demo_leftover_reads.fastq.2.gz
-rwxrwx--- 1 user group.GRP 481K May 22 10:40 BT474-demo.psl
-rwxrwx--- 1 user group.GRP   83 May 22 10:40 log_blat
-rwxrwx--- 1 user group.GRP 6.5K May 22 10:42 log_filter
```

**Comment by leiendeckerlu** [comment]
and here comes the JAFFA directory:
```
-rwxrwxr-x  1 user group.GRP 2.3K Nov 22 12:43 assemble.sh
drwxrwx---  2 user group.GRP  473 May 22 10:42 BT474-demo
-rwxrwx---  1 user group.GRP   43 May 17 21:35 checks
drwxrwx---  2 user group.GRP  18K May 17 21:18 chroms
-rwxrwx---  1 user group.GRP 300K May 22 10:42 commandlog.txt
-rwxrwxr-x  1 user group.GRP 2.4K Nov 22 12:43 compile_results.R
drwxrwx---  2 user group.GRP   78 May 22 09:12 Demo_Data
-rwxrwxr-x  1 user group.GRP 1.1K Nov 22 12:43 get_spanning_reads_for_direct_1.R
-rwxrwxr-x  1 user group.GRP  999 Nov 22 12:43 get_spanning_reads_for_direct_2.R
-rwxrwxr-x  1 user group.GRP 1.6K Nov 22 12:43 get_spanning_reads.R
-rwxrwx---  1 user group.GRP 939M Jan 24  2014 hg38.chromFa.tar.gz
-rwxrwx---  1 user group.GRP 3.1G May 17 21:20 hg38.fa
-rwxrwxr--  1 user group.GRP 125M Jun 19  2015 hg38_genCode22.1.bt2
-rwxrwxr--  1 user group.GRP  71M Jun 19  2015 hg38_genCode22.2.bt2
-rwxrwxr--  1 user group.GRP 1.7M Jun 19  2015 hg38_genCode22.3.bt2
-rwxrwxr--  1 user group.GRP  71M Jun 19  2015 hg38_genCode22.4.bt2
-rwxrwxr--  1 user group.GRP 308M Jun 19  2015 hg38_genCode22.fa
-rwxrwxr--  1 user group.GRP 125M Jun 19  2015 hg38_genCode22.rev.1.bt2
-rwxrwxr--  1 user group.GRP  71M Jun 19  2015 hg38_genCode22.rev.2.bt2
-rwxrwxr--  1 user group.GRP  41M Jun 19  2015 hg38_genCode22.tab
-rwxrwxr--  1 user group.GRP 100K May 21 15:19 hs_err_pid1747.log
-rwxrwxr--  1 user group.GRP 100K May 21 15:19 hs_err_pid1758.log
-rwxrwxr--  1 user group.GRP 100K May 21 15:20 hs_err_pid1761.log
-rwxrwxr--  1 user group.GRP 100K May 21 15:19 hs_err_pid2259.log
-rwxrwxr--  1 user group.GRP  99K May 21 15:19 hs_err_pid2395.log
-rwxrwxr--  1 user group.GRP 100K May 21 15:19 hs_err_pid2488.log
-rwxrwxr--  1 user group.GRP 100K May 21 15:19 hs_err_pid2575.log
-rwxrwxr--  1 user group.GRP 100K May 21 15:19 hs_err_pid3131.log
drwxrwx---  2 user group.GRP   70 May 17 18:35 input
-rwxrwxr-x  1 user group.GRP 4.6K May 17 18:13 install_linux64.sh
-rwxrwxr-x  1 user group.GRP 1.3K Nov 22 12:43 JAFFA_assembly.groovy
-rwxrwxr-x  1 user group.GRP 1.5K Nov 22 12:43 JAFFA_direct.groovy
-rwxrwxr-x  1 user group.GRP 1.7K Nov 22 12:43 JAFFA_hybrid.groovy
-rwxrwx---  1 user group.GRP    0 May 21 14:34 JAFFA.o4302224
-rwxrwx---  1 user group.GRP 142K May 22 03:35 JAFFA.o4302228
-rwxrwx---  1 user group.GRP    0 May 22 08:26 JAFFA.o4302371
-rwxrwx---  1 user group.GRP    0 May 21 14:34 JAFFA.po4302224
-rwxrwx---  1 user group.GRP    0 May 21 15:16 JAFFA.po4302228
-rwxrwx---  1 user group.GRP    0 May 22 08:26 JAFFA.po4302371
-rwxrwx---  1 user group.GRP 2.4K May 21 14:16 jaffa_results.csv
-rwxrwx---  1 user group.GRP 1.9K May 21 14:16 jaffa_results.fasta
-rwxrwxr-x  1 user group.GRP  22K May 22 08:24 JAFFA_stages.groovy
-rwxrwx---  1 user group.GRP  22K May 18 09:34 JAFFA_stages.groovy_backup
-rwxrwxr-x  1 user group.GRP  25K Nov 22 12:43 known_fusions.txt
-rwxrwxr-x  1 user group.GRP  14K Nov 22 12:43 make_final_table.R
-rwxrwxr--  1 user group.GRP 939M Mar  4  2015 Masked_hg38.1.bt2
-rwxrwxr--  1 user group.GRP 699M Mar  4  2015 Masked_hg38.2.bt2
-rwxrwxr--  1 user group.GRP 2.6M Mar  4  2015 Masked_hg38.3.bt2
-rwxrwxr--  1 user group.GRP 699M Mar  4  2015 Masked_hg38.4.bt2
-rwxrwxr--  1 user group.GRP 939M Mar  4  2015 Masked_hg38.rev.1.bt2
-rwxrwxr--  1 user group.GRP 699M Mar  4  2015 Masked_hg38.rev.2.bt2
-rwxrwxr-x  1 user group.GRP 4.5K Nov 22 12:43 process_transcriptome_blat_table.R
-rwxrwxr-x  1 user group.GRP  618 Nov 22 12:43 README
-rwxrwxr--  1 user group.GRP  713 Nov 22 12:43 README.md
drwxrwx--- 15 user group.GRP  931 May 19 10:28 R-patched
-rwxrwx---  1 user group.GRP  78M May 19 10:09 R-patched.tar.gz
-rwxrwx---  1 user group.GRP  982 May 22 10:42 runJAFFA.sh
-rwxrwx---  1 user group.GRP    0 May 22 18:06 runJAFFA.sh.save
-rwxrwx---  1 user group.GRP  969 May 22 18:06 runJAFFA.sh.save.1
drwxrwx--- 11 user group.GRP  254 May 17 18:18 tools
-rwxrwx---  1 user group.GRP  985 May 17 18:18 tools.groovy
```

**Comment by nadiadavidson** [comment]
Thanks for that. It looks like you run into trouble at the process_transcriptome_blat stage. There's a known bug in JAFFA which makes it incompatible with newer versions of R. Can you try to install JAFFA version 1.09, https://github.com/Oshlack/JAFFA/releases to see if this fixes the problem? 

Cheers,
Nadia.

**Comment by leiendeckerlu** [comment]
Great, will check that!
Will let you know how it goes.
Lukas

**Comment by leiendeckerlu** [comment]
well, the demo samples worked smoothly with 1.09, will try my own samples now!
Looks good :)

**Comment by leiendeckerlu** [comment]
Did you remove the "threads" option in 1.09 ? And if so, why? Or is it still implemented but not defined in JAFFA_stages.groovy ?

**Comment by vinegang** [comment]
I have the same question. is it possible to set the number of threads in version 1.09. I am trying to run JAFFA on a sample, it ran for 10hrs and failed, due to time limit.
