### ISSUE TITLE
Error: Please use 'drop.self' and/or 'drop.redundant' instead of the   'ignoreSelf' and/or 'ignoreRedundant' arguments. Execution halted

### ISSUE THREAD

**Issue by ndaniel** [Oshlack/JAFFA#31]
When running JAFFA v1.0.8 and hg38 this command executed by JAFFA:
```
================================= Stage filter_transcripts (reads) =================================
ERROR: Command failed with exit status = 1 : 

time /usr/bin/R --vanilla --args reads/reads.psl reads/reads.txt 1000 /apps/bin/jaffa/hg38_genCode22.tab <  /apps/bin/jaffa/process_transcriptome_blat_table.R &> reads/log_filter 

```
gives this error (when re-run the command from above manually in terminal):
```
> candidates=do.call("rbind",lapply(split_results,multi_gene))
Error: Please use 'drop.self' and/or 'drop.redundant' instead of the
  'ignoreSelf' and/or 'ignoreRedundant' arguments.
Execution halted
```
[Here](https://www.dropbox.com/s/4rjdlbqepd05gd3/reads.psl?dl=0) is the `reads/reads.psl` file.

How to fix this?

**Comment by nadiadavidson** [comment]
Hi,

We've fixed this in github but haven't made a release with it yet. If you replace the github file, process_transcriptome_blat_table.R, with the copy you have it should solve the problem.

The bug comes from changes in the latest R/bioconductor.

Cheers,
Nadia.

**Comment by ndaniel** [comment]
That's fixed it!
