### ISSUE TITLE
Issue 31, take 2: Error: Please use 'drop.self' and/or 'drop.redundant' instead of the 'ignoreSelf' and/or 'ignoreRedundant' arguments

### ISSUE THREAD

**Issue by NThio** [Oshlack/JAFFA#34]
Bumped to the error above (as reported at Issue 31), running v1.07 and v1.08 after upgrading bioconductor package. Replacing the R script as described with master branch removed the error, however later stages failed with empty result. 

Resolution on Issue 31 perhaps correct at the time, however I can't get which commit it was referring to. IMHO the alternative resolutions is to stick with IRanges v2.6.1 R package (either using local installation or packrat) when using jaffa v1.07 or v1.08; or to move to 1.09 completely.

**Comment by nadiadavidson** [comment]
Release v1.09 has been available since May and should be used instead of the suggestion in closed issue #31.
