### ISSUE TITLE
Interpreting output .csv

### ISSUE THREAD

**Issue by leeprichman** [Oshlack/JAFFA#35]
Hi all,
Thanks so much for putting this package out there.  I had a question about the contig_break column in the output csv.  Does that indicate that the break is before or after that particular base? In other words if the contig break is 55, is the break between bases 54-55 or bases 55-56 of the read?
Thanks!

**Comment by nadiadavidson** [comment]
I believe it should be after, so 55-56 in your example. In the jaffa_results.fasta file produced by JAFFA the bases before and after the break are in lower case. You could use this is double check if unsure.

**Comment by leeprichman** [comment]
Awesome, that does appear to be the case.  I probably could have figured this out without bothering anyone if I had read the documents more closely... 

Thanks for the help!
