### ISSUE TITLE
Issue fetching BLAT inside of install_linux64.sh

### ISSUE THREAD

**Issue by jcursons** [Oshlack/JAFFA#38]
I had some issues using the shell script to install dependencies - specifically BLAT:

--2018-01-08 17:28:01--  http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/blat/blat
Resolving hgdownload.cse.ucsc.edu (hgdownload.cse.ucsc.edu)... 128.114.119.163
Connecting to hgdownload.cse.ucsc.edu (hgdownload.cse.ucsc.edu)|128.114.119.163|:80... connected.
HTTP request sent, awaiting response... Read error (Connection timed out) in headers.
Retrying.

The link is still valid so I'm not sure if the page headers have been updated causing an issue with wget? I had a look in install_linux64.sh at the final path, and the easiest workaround was just to manually download blat and put it inside of /bin.

Thanks for your great documentation!

**Comment by nadiadavidson** [comment]
Looks like this issue was a one-off (perhaps the site was down?)
Closing the issue.
