### ISSUE TITLE
jaffa use on singular samples

### ISSUE THREAD

**Issue by bioinfo-dirty-jobs** [Oshlack/JAFFA#40]
I want to run jaffa for each sample at time and for do that I need to write in differen way the input
I use the last relase on bioconda..

`
 java-direct  RAW/343_R1.gz RAW/343_R2.gz `

How can do this?

**Comment by nadiadavidson** [comment]
I'm not sure how it's implemented in bioconda, but in regular JAFFA you can just specify the file names like in your example. Did you get this to work? If so I will close the issue.
Cheers,
Nadia.
