### ISSUE TITLE
JAFFA is breaking at the last step - compiling the results

### ISSUE THREAD

**Issue by serine** [Oshlack/JAFFA#47]
Hi Nadia, 

Not sure if there is a bug somewhere in the [last stage](https://github.com/Oshlack/JAFFA/blob/c2ebffdeb2b0ad3518fb77a3e966a10c28760507/JAFFA_stages.groovy#L516) or I just been unlike, but I can get JAFFA to exit cleanly.

this is the actual error message 

```
Fatal error: cannot open file 'jaffa_results': No such file or directory
``` 

Not gonna post verbose version as it contains sample names. 

That final stage has three parts.

- `compile_results.R` function that gives:
    - `jaffa_results.csv`
    - `jaffa_results.temp`
- `get_sequences` BASH function in a while loop over each fusion event
- and a bit of cleaning up

I'm fairly confident that `get_sequences` BASH function is somehow broken. I spent a while trying to pin point exactly which part, but couldn't. I'm guessing that it is todo with BASH version and/or some other environmental variables settings like internal field separator (IFS).

I re-wrote that function a little

```
function get_seq() {

  type=""
  output_name="jaffa_results"

  field1=$(echo ${1} | tr -d '"')
  field2=$(echo ${2} | tr -d '"')
  field3=$(echo ${3} | tr -d '"')
  field4=$(echo ${4} | tr -d '"')
  #field3=$(echo ${15} | tr -d '"')
  #field4=$(echo ${16} | tr -d '"')

  if [[ ${field1} =~ "sample" ]]
  then
    return
  fi

  fusions_file=${field1}/${field1}${type}.fusions.fa

  new_id=${field1}---${field2}---${field3}
  echo ">$new_id" >> ${output_name}.fasta
  brk_pnt=${field4}

  #sequence=$(grep -A1 "^>${field3}" ${fusions_file} | grep -v "^>")
  sequence=$(grep -A1 "^>${field3}" ${fusions_file} | grep -v ">")

  start=$(echo $sequence | cut -c 1-$((${brk_pnt}-1)))
  middle=$(echo $sequence | cut -c $brk_pnt-$((${brk_pnt}+1)) | tr '[:upper:]' '[:lower:]')
  string_length=$(echo ${#sequence})

  end=$(echo ${sequence} | cut -c $((${brk_pnt}+2))-${string_length})

  echo ${start}${middle}${end} >> ${output_name}.fasta
}

export -f get_seq
```

Note that it took me a bit of time to figure out that your `temp` file was there for the while loop step. I originally got the same information from the `.csv` file directly. (temp file seems a bit redundant here). Also `.csv` and `.temp` have different IFS. The reason I switched to `.csv` is because I couldn't get `.temp` line to tokenize correctly inside the function. Like I said I think it is something to do with IFS env variable. Anyway I think it would be cleaner if that BASH blob was in a separate file which gets called in, instead of in-lining it in, which look scary with all the escaping and semi-colon characters. 
Also note that for some reason `grep -v "^>"` wasn't working for me, again that doesn't make too much sense, but simply `grep -v ">"` worked ok. I understand that we want to force lines that start with `>`, like I said feels like env or versioning problem.

I basically ran `compile_results.R` and that while loop manually to get

- `jaffa_results.csv`
- `jaffa_results.fasta`

Just FYI 

```
Rscript --vanilla ~/downloads/JAFFA/compile_results.R jaffa_results */**.summary
source get_seq.bash 
while read l;do get_seq $l;done < <(tr '\t' ',' < jaffa_results.temp)
```  

Thanks

p.s feel free to close this issue right away, this is mainly to surface the problem(s) that I had with getting pipeline to run and some extra notes for other users, cheers.

**Comment by nadiadavidson** [comment]
Hi Thank for this. Yes that bit of code is not the most elegant!
Please feel free to submit a pull request to the repository if you like.
What system are you running on?

Cheers,
Nadia.

**Comment by serine** [comment]
This specs

```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
```
```
java --version
openjdk 11.0.3 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu218.04.1)
OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu218.04.1, mixed mode, sharing)
```
```
bash --version
GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by serine** [comment]
that bug that was causing me problems was self inflicted, so I don't think there was anything wrong with that BASH blob, still nicer to have it as an external function. cheers
