### ISSUE TITLE
True 120 Fusions MiSeq Dataset 

### ISSUE THREAD

**Issue by Evansef** [Oshlack/JAFFA#49]
Hello, I would like to know where I could find the list of the 120 true fusions which are in the MiSeq dataset. I searched in the publication but I didn't find it. 

Thank you in advance for your answer.

**Comment by nadiadavidson** [comment]
Hi,
If you go to the wiki page "Downloads" you should find a link to three files associated with the MiSeq dataset (2 read end files + a file with truth information).

Cheers,
Nadia.

**Comment by Evansef** [comment]
Thank you very much !
