### ISSUE TITLE
Failing at stage run_check

### ISSUE THREAD

**Issue by SamHill95** [Oshlack/JAFFA#50]
Hi there,

I've recently installed JAFFA as per the github instructions. I have downloaded the hg19.fa.gz and the hg19-genCode19 JAFFA reference tarball and gunzipped/unpacked respectively. All resulting files I have moved to the JAFFA directory as advised to help things run smoothly with the script.

I'm running the following command (with paths specified correctly for corresponding files);

bpipe run -p genome=hg19 -p annotation=genCode19 ../JAFFA_assembly.groovy ../../../data/catdata

But I keep getting an error at the run_check stage

# Starting pipeline at Sun Feb 23 21:16:40 GMT 2020
# Input files:  ../../../data/catdata
# Output Log:  .bpipe/logs/189483.log
# Stage run_check
echo "Running JAFFA version 1.09" ;             echo "Checking for required data files..." ;             for i in /scratch/c.c1891802/bin/JAFFA/JAFFA-version-1.09/JAFFArun1/../hg19_genCode19.fa /scratch/c.c1891802/bin/JAFFA/JAFFA-version-1.09/JAFFArun1/../hg19_genCode19.tab /scratch/c.c1891802/bin/JAFFA/JAFFA-version-1.09/JAFFArun1/../known_fusions.txt /scratch/c.c1891802/bin/JAFFA/JAFFA-version-1.09/JAFFArun1/../hg19.fa /scratch/c.c1891802/bin/JAFFA/JAFFA-version-1.09/JAFFArun1/../Masked_hg19.1.bt2 /scratch/c.c1891802/bin/JAFFA/JAFFA-version-1.09/JAFFArun1/../hg19_genCode19.1.bt2 ;                   do ls $i 2>/dev/null || { echo "CAN'T FIND $i..." ;              echo "PLEASE DOWNLOAD and/or FIX PATH... STOPPING NOW" ; exit 1  ; } ; done ;             echo "All looking good" ;             echo "running JAFFA version 1.09.. checks passed" > checks
# ################ Finished at Sun Feb 23 21:16:41 GMT 2020 Duration = 0.924 seconds #################

I'm struggling to pick out what exactly is missing, if anything; guidance would be appreciated!

Thanks

**Comment by nadiadavidson** [comment]
Hi, can you please do an "ls -l" in the directory where the references are and send the output?
Hopefully it will be something simple we can fix.

**Comment by SamHill95** [comment]
Hi,

Thanks for your reply; the initial error has been fixed (for some reason the symbolic links to the reference files weren't sufficient so I moved the files themselves to the JAFFA directory).

I am now, however, getting an execution halted error at the filter_transcripts stage when running the pipeline which reads the following in the log_filter file;

Error in library(IRanges) : there is no package called ‘IRanges’
Execution halted

I have R installed and the IRanges package installed/loaded so I'm not sure where the problem is?

Thanks

**Comment by nadiadavidson** [comment]
That sounds strange. Are you running on a cluster? Perhaps IRanges isn't installed on the nodes?

**Comment by SamHill95** [comment]
Logged into a cluster yes, but I've manually installed R and subsequently IRanges to my working scratch directory; I've also 'downgraded' JAFFA to 1.0.8 to see if that would help but no luck still!

With the JAFFA 1.0.8 version however I'm getting exit status 127 with this in the log_filter file;

/apps/languages/R/3.5.1/el7/AVX512/intel-2018/lib64/R/bin/exec/R: error while loading shared libraries: libifport.so.5: cannot open shared object file: No such file or directory

Is there a manual workaround for this? It seems this filtering step is one of the final stages of the script which is painful to keep failing at!

Thanks for your help

**Comment by nadiadavidson** [comment]
One thing you could try is to run the bpipe command manually. To do this, instead of typing the bpipe command to run, replace "bpipe run" with "bpipe test". It should print out some information including the next command to be run. You can then copy and paste it into a terminal. I suspect it might still give you an error, but at least would give you a way to work out what's happening with your R installation. The filtering step is actually midway through the JAFFA pipeline and there are several filtering steps after this, some of which also use R, so there's a chance you might also run into troubles with those also.

I have actually been working on a version of JAFFA that performs this step without using R. The code is likely to be a few months away from being tested and released, but I let you know when that happens if you like.

**Comment by SamHill95** [comment]
Your help is much appreciated, thank you.

I will try the manual method and see where I stand.

I would be interested in testing the code you're currently working on, do please keep me informed (if it isn't too much trouble!)

**Comment by SamHill95** [comment]
I've edited the path to R that was populated in the tools.groovy file; it had populated as my cluster's R instance, but I use the R in my personal directory (which contains the IRanges module) so I'm hoping this fixes the issue; I'll close this out now as the original issue has been solved.

Thanks
