### ISSUE TITLE
The reference file version problem

### ISSUE THREAD

**Issue by GAOwy123** [Oshlack/JAFFA#55]
Whether I could use other genecode reference files, such as genecode v37lift37 ? Or I must download https://figshare.com/articles/JAFFA_REFERENCE_FILES_HG19_GENCODE19_tar_gz?

**Comment by nadiadavidson** [comment]
Hi, 

I'd highly recommend using the reference files provided if you can. If you can't, you can follow the instructions here, https://github.com/Oshlack/JAFFA/wiki/FAQandTroubleshooting#how-can-i-generate-the-reference-files-for-a-non-supported-genome to create your own. Not that you'll need to be using JAFFA version 1 (not 2) to use the hg19 reference files provided or your own.

Cheers,
Nadia.

**Comment by GAOwy123** [comment]
Thank you for your reply.  I will try.
