### ISSUE TITLE
hg19 reference files for JAFFA version 2

### ISSUE THREAD

**Issue by nadiadavidson** [Oshlack/JAFFA#56]
Make reference for hg19 available (also mouse?)

See if reference tar ball can be made smaller (e.g. some of the files generated locally)

**Comment by GAOwy123** [comment]
How to change the reference file to hg19(in version 1.09)?

**Comment by nadiadavidson** [comment]
> How to change the reference file to hg19(in version 1.09)?
There are some instructions here,
[https://github.com/Oshlack/JAFFA/wiki/FAQandTroubleshooting#how-can-i-use-a-genome-other-than-hg38](https://github.com/Oshlack/JAFFA/wiki/FAQandTroubleshooting#how-can-i-use-a-genome-other-than-hg38)

**Comment by nadiadavidson** [comment]
Update: instruction on how to make the reference files for version 1.0 compatible with version 2.0 are now provided in FAQ on the wiki.
