### ISSUE TITLE
error at stage filter_transcripts

### ISSUE THREAD

**Issue by mei-du** [Oshlack/JAFFA#58]
Hi team,

I've run into a std::regex_error when running JAFFAL with default parameters and the provided hg38 reference. The same error occurred with both ONT and PacBio data. Any clarification would be much appreciated, thank you!

![JAFFAL error](https://user-images.githubusercontent.com/58542302/118220405-f6109580-b4be-11eb-86f0-2108d857f2c3.png)

**Comment by nadiadavidson** [comment]
Hi,
This looks like the same error as issue #57. I believe this is resolved if you switch to gcc version 4.9 or higher and reinstall JAFFA (remove the tools directory and rerun the installation script). Please let us know if that works for you.

Cheers,
Nadia.

**Comment by mei-du** [comment]
Hi @nadiadavidson, that worked but I encountered another error during genome mapping.

![image](https://user-images.githubusercontent.com/58542302/118231087-f23a3e80-b4d1-11eb-9ec7-eef1c16cd872.png)

**Comment by nadiadavidson** [comment]
Hi,
Did you remove the old run with the std::regex_error? I wonder if rerunning from that point would create some empty files that might give you this error. Can you please send me the result of "ls -l" in the sample directory where the results are being written. ie:
ls -l S6R_polyA*.fastq/
Cheers,
Nadia.

**Comment by mei-du** [comment]
Hi Nadia
You were right about the empty files. I removed them and re-installed the tools just in case. The pipeline was working well until the genome mapping stage.  This has happened twice.

<img width="1183" alt="Screen Shot 2021-05-14 at 16 50 46" src="https://user-images.githubusercontent.com/58542302/118258583-63d6b480-b4f3-11eb-8b2d-742bf3ca23ae.png">

<img width="1186" alt="Screen Shot 2021-05-14 at 20 29 33" src="https://user-images.githubusercontent.com/58542302/118258562-5f120080-b4f3-11eb-93f3-4bfe6ce4afe2.png">

**Comment by nadiadavidson** [comment]
Hi,
It sounds like you removed all the results file which were empty within "S1R_...ccs.fastq", and then reran is that right? It's odd that the .txt file is still empty after rerunning. Can you send me the results of ls -l inside the directory were you placed the reference files? Even with non-tumour samples, the .txt file usually has a few candidates reported, so it's very usually that that stage would complete okay and the output be empty. Is there anything usual about your sample? 

Have you been able to run JAFFAL or any of JAFFA's other modes on other dataset (e.g the short read demo data or long read simulation from https://github.com/Oshlack/JAFFA/wiki/Example)?

If you can send me your .paf file, or any reproducible example, I'm happy to investigate what's going on.

Cheers,
Nadia.

**Comment by mei-du** [comment]
Hi Nadia,
Sorry the `ls -l` image I sent was before removing and rerunning. 

References:
![image](https://user-images.githubusercontent.com/58542302/118608875-8885a180-b7fd-11eb-9692-3f6dc408391f.png)

I was able to successfully run JAFFA assembly, direct and hybrid on the demo data.

I'm getting the same error with JAFFAL and the long read simulation data, just during the minimap2_genome stage:
![image](https://user-images.githubusercontent.com/58542302/118614858-858daf80-b803-11eb-96b5-3f9ac17be56c.png)

**Comment by mei-du** [comment]
Hi Nadia, sending a link to my JAFFAL outputs run with the simulation data.
https://drive.google.com/drive/folders/19_1ZLdTX4Z9DeqN4uU0iJ_bB-ZnhO6ML?usp=sharing

**Comment by nadiadavidson** [comment]
Thanks! Everything prior to the minimap2 aligning to the genome looks perfect. I'm now wondering if minimap2 might have run out of memory. How much memory do you give the job? JAFFAL needs about 20GB per sample, so you could set to 25GB to be safe.

**Comment by mei-du** [comment]
Ah yes, I think that did the trick! I tried 2 samples with 50GB. Thanks so much for your help!
![image](https://user-images.githubusercontent.com/58542302/118896654-0e176780-b94c-11eb-865b-bb1c1b99a678.png)

**Comment by nadiadavidson** [comment]
Glad to hear it! and happy to help if you run into any other errors.
