### ISSUE TITLE
JAFFAL output

### ISSUE THREAD

**Issue by Lux91** [Oshlack/JAFFA#59]
Hi, I just started using JAFFAL to find fusion genes in ONT cDNA sequencing. I was wondering, what is the difference between the "SampleA.fastq.summary" output and the "jaffal_result.csv" output?
Which one should I refer to if I want to start designing experiments to validate my result?
Thanks in advance for the help :)

**Comment by nadiadavidson** [comment]
Hi, 

jaffa_results.csv should be a reformatted and reordered version of the information in "SampleA.fastq.summary". jaffa_results.csv is usually the output you'd look at. If you are seeing known fusions in the .summary file that aren't reported in .csv file, let me know as that sounds like a bug. If you run JAFFAL on multiple samples, each will have its own .summary file and they will be compiled together in the jaffa_results.csv file. 

Hope this info is useful.

Cheers,
Nadia.

**Comment by Lux91** [comment]
Thank you very much, the discrepancy I was seeing was just my mistake, I was looking at 2 files from 2 samples.
Thanks again for the clarification.

Lucas :)
