### ISSUE TITLE
failed for 1 sample only

### ISSUE THREAD

**Issue by mei-du** [Oshlack/JAFFA#60]
Hi Nadia,
I have 6 ONT samples and was able to run JAFFAL successfully on 5 of them. Tried deleting output files and re-running on the 1 remaining sample but that also did not work. Do you perhaps have any potential solutions?

These are the full samples of the subsampled data I used in #58 so I am hoping it's not an issue with the fastq file. Let me know if any extra information is required. Thank you!

**Comment by nadiadavidson** [comment]
Hi, 
What error does it give?
Cheers,
Nadia.

**Comment by mei-du** [comment]
When I ran JAFFAL on this sample separately, it gave these errors but when I did the run on all samples previously I only got the final 'Pipeline Failed' section. 
> =================================== Stage get_fasta (barcode05) ====================================
> java -ea -Xmx200m -cp [redacted]/JAFFA-version-2.1/tools/bbmap/current/ jgi.ReformatReads ignorebadquality=t in=[redacted]/barcode01-06/barcode05.fq.gz out=barcode05.fq/barcode05.fq.fasta threads=16
> Executing jgi.ReformatReads [ignorebadquality=t, in=[redacted]/barcode01-06/barcode05.fq.gz, out=barcode05.fq/barcode05.fq.fasta, threads=16]
> Set threads to 16
> Input is being processed as unpaired
> Warning! Changed from ASCII-33 to ASCII-64 on input 9: 57 -> 26
> Up to 404 prior reads may have been generated with incorrect qualities.
> If this is a problem you may wish to re-run with the flag 'qin=33' or 'qin=64'.
> Exception in thread "Thread-8" java.nio.file.NoSuchFileException: ./._run_jaffal_ont.sh
> 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
> 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
> 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
> 	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
> 	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
> 	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
> 	at java.nio.file.Files.readAttributes(Files.java:1737)
> 	at java.nio.file.Files.getLastModifiedTime(Files.java:2266)
> 	at sun.reflect.GeneratedMethodAccessor91.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
> 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
> 	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.invoke(StaticMetaMethodSite.java:46)
> 	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:91)
> 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
> 	at bpipe.OutputDirectoryWatcher.processEvent(OutputDirectoryWatcher.groovy:139)
> 	at bpipe.OutputDirectoryWatcher$processEvent$1.callCurrent(Unknown Source)
> 	at bpipe.OutputDirectoryWatcher.run(OutputDirectoryWatcher.groovy:122)
> Input:                  	48219467 reads          	26277991830 bases
> Output:                 	48219467 reads (100.00%) 	26277991830 bases (100.00%)
> Time:                         	683.221 seconds.
> Reads Processed:      48219k 	70.58k reads/sec
> Bases Processed:      26277m 	38.46m bases/sec
> Exception in thread "main" java.lang.RuntimeException: ReformatReads terminated in an error state; the output may be corrupt.
> 	at jgi.ReformatReads.process(ReformatReads.java:1103)
> 	at jgi.ReformatReads.main(ReformatReads.java:43)
> ERROR: Command failed with exit status = 1 : 
> 
> [redacted]/JAFFA-version-2.1/tools/bin/reformat ignorebadquality=t in=[redacted]/barcode01-06/barcode05.fq.gz out=barcode05.fq/barcode05.fq.fasta threads=16 ; 
> 
> 
> ========================================= Pipeline Failed ==========================================
> 
> One or more parallel stages aborted. The following messages were reported: 
> 
> Branch barcode05.fq in stage Unknown reported message:
> 
> Command failed with exit status = 1 : 
> 
> [redacted]/JAFFA-version-2.1/tools/bin/reformat ignorebadquality=t in=[redacted]/barcode01-06/barcode05.fq.gz out=barcode05.fq/barcode05.fq.fasta threads=16 ;
> 
> Use 'bpipe errors' to see output from failed commands.

**Comment by nadiadavidson** [comment]
Thanks, I've seen things like this before when the fastq file had unusual characters or spaces in it, but only ever with ONT data. Which base callers was the file generated with? JAFFAL should also be able to take a .fasta file, so you may be able to get it to run if you can convert the file to fasta yourself?

**Comment by mei-du** [comment]
Guppy version 3.2.8 was used. I'll try converting to fasta, thanks!

**Comment by mei-du** [comment]
Hi Nadia, I converted to fasta but when running all samples together, sample 5 didn't seem to have been picked up but then it eventually produced a similar-looking error down the line, so I ran it independently and that worked.

**Comment by nadiadavidson** [comment]
Yes, if you run all the samples in parallel they need to be the same type. Glad to hear it worked finally.
