### ISSUE TITLE
extract_seq_from_fasta not getting installed

### ISSUE THREAD

**Issue by Troyee13** [Oshlack/JAFFA#63]
Hello,

When I am manually trying to install

g++ -O3 -o bin/extract_seq_from_fasta ../src/extract_seq_from_fasta.c++

I am getting this error:

In file included from /usr/include/c++/4.8.2/unordered_set:35:0,
                 from ../src/extract_seq_from_fasta.c++:19:
/usr/include/c++/4.8.2/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
../src/extract_seq_from_fasta.c++: In function ‘int main(int, char**)’:
../src/extract_seq_from_fasta.c++:41:3: error: ‘unordered_set’ was not declared in this scope
   unordered_set<string> ids_to_keep;
   ^
../src/extract_seq_from_fasta.c++:41:23: error: expected primary-expression before ‘>’ token
   unordered_set<string> ids_to_keep;
                       ^
../src/extract_seq_from_fasta.c++:41:25: error: ‘ids_to_keep’ was not declared in this scope
   unordered_set<string> ids_to_keep;
                         ^

My g++ version is
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)

Please suggest how to resolve this.

**Comment by Troyee13** [comment]
I tried running the installation on a different server with gccversion
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609

Still getting the same error.

**Comment by nadiadavidson** [comment]
Hi,

Can you please try running the command:
g++ -O3 -std=c++11 -o bin/extract_seq_from_fasta ../src/extract_seq_from_fasta.c++
and let me know if that compiles.
Cheers,
Nadia.

**Comment by Troyee13** [comment]
Thanks for the reply. 
g++ -O3 -std=c++11 -o bin/extract_seq_from_fasta ../src/extract_seq_from_fasta.c++
This command actually worked for gcc 5.4.0 and I was able to run the demo data.
I have also upgraded gcc from 4.8.5 to  7.3.0 and everything got installed without any warning. I have run my own data in direct mode. Everything is working out well till now. Thanks again.
