### ISSUE TITLE
zero size output

### ISSUE THREAD

**Issue by aheravi** [Oshlack/JAFFA#66]
Hi,
I tried JAFFAL (JAFFA-version-2.1) on my ONT reads and got zero-size files, below. Is that due to no fusion found in the data or something else?

Thanks,
Ali

Running command:
```
JAFFA-version-2.1/tools/bin/bpipe run /JAFFA-version-2.1/JAFFAL.groovy ./Data/*fastq.gz
```

Outputs:
```
0 Aug 19 16:26 test.fastq.summary
74 Aug 19 16:26 test.fastq.reads
0 Aug 19 16:26 test.fastq_genome.psl
0 Aug 19 16:24 test.fastq_genome.paf
0 Aug 19 16:09 test.fastq.fusions.fa
0 Aug 19 15:33 test.fastq.txt
11G Aug 19 15:33 test.fastq.paf
17G Aug 19 15:14 test.fastq.fasta
```

**Comment by nadiadavidson** [comment]
Hi Ali,
It looks like something has gone wrong. Can you please delete everything apart from "test.fastq.paf" and "test.fastq.fasta". Then rerun the command in "test" mode:
JAFFA-version-2.1/tools/bin/bpipe test /JAFFA-version-2.1/JAFFAL.groovy ./Data/*fastq.gz

It should print the next command it would run. Something like "process_transcriptome_align_table ...."
Can you then try to run just this command and tell me if you get an error and/or empty file "test.fastq.txt".

There is a known issue with this stage when process_transcriptome_align_table has been compiled with a gcc version below 4.9 although JAFFAL would usually halt at this point and give an error.

Cheers,
Nadia.
