### ISSUE TITLE
jaffal error when using a non-supported genome

### ISSUE THREAD

**Issue by Aurore-B** [Oshlack/JAFFA#69]
Hi,
Thanks for providing this interesting tool !

I tried JAFFAL using `JAFFA-version-2.2.0` on conda environment with `gcc version 9.4.` on 2 types of ONT data: **human** and **dog**.
It worked well when I used the example data (simulated data from JAFFAL paper) and when I used my own human data with hg38 JAFFA default reference but I got an issue on my dog data.
First, I followed the method from FAQ to generate reference files for a non-supported genome.
Then, I ran the following code:
```
$JAFFA_DIR/tools/bin/bpipe run -p readLayout=“single” -p genome=canFam4 -p annotation=UU_Cfam_GSD_1.0 -p refBase=$CANFAM_REF $JAFFA_DIR/JAFFAL.groovy $INDIR_FASTQ/*.fastq.gz
```
I obtained an error similar to issue #57 but not exactly the same :
```
================================ Stage filter_transcripts (vico_R1) ================================
Done reading in transcript IDs
Reading the input alignment file, vico_R1.fastq/vico_R1.fastq.paf
terminate called after throwing an instance of ‘std::out_of_range’
  what():  map::at
bash: line 1: 153335 Aborted                 (core dumped) /groups/dog/aurore/test_JAFFAL/conda_env/JAFFAL_env
/share/jaffa-2.2-0/tools/bin/process_transcriptome_align_table vico_R1.fastq/vico_R1.fastq.paf 1000 /groups/dog/aurore/test_JAFFAL/REF_canFam4/canFam4_UU_Cfam_GSD_1.0.tab > vico_R1.fastq/vico_R1.fastq.txt
ERROR: Command failed with exit status = 134 :
/groups/dog/aurore/test_JAFFAL/conda_env/JAFFAL_env/share/jaffa-2.2-0/tools/bin/process_transcriptome_align_ta
ble vico_R1.fastq/vico_R1.fastq.paf 1000 /groups/dog/aurore/test_JAFFAL/REF_canFam4/canFam4_UU_Cfam_GSD_1.0.ta
b > vico_R1.fastq/vico_R1.fastq.txt
========================================= Pipeline Failed ==========================================
One or more parallel stages aborted. The following messages were reported:
Branch vico_R1.fastq in stage Unknown reported message:
Command failed with exit status = 134 :
conda_env/JAFFAL_env/share/jaffa-2.2-0/tools/bin/process_transcriptome_align_ta
ble vico_R1.fastq/vico_R1.fastq.paf 1000 REF_canFam4/canFam4_UU_Cfam_GSD_1.0.ta
b > vico_R1.fastq/vico_R1.fastq.txt
```
Here is preview on my file `vico_R1.fastq.paf`
```
head -3 vico_R1.fastq.paf`
10ba6f39-4f1d-469b-b77c-06c71bd3610c    302 80  260 -   canFam4_refGene_NM_001003024__range=chr9:34321863-34352772__5'pad=0__3'pad=0__strand=-__repeatMasking=none  2214    2020    2209    165 194 60  NM:i:29 ms:i:224    AS:i:224    nn:i:0  tp:a:P  cm:i:14 s1:i:90 s2:i:0  de:f:0.0934 rl:i:26 cg:Z:5M1I37M1I5M2I2M1I65M2D15M10D35M2D11M
42b3f838-c198-483a-a822-ba3de68482f0    313 83  272 -   canFam4_refGene_NM_001003024__range=chr9:34321863-34352772__5'pad=0__3'pad=0__strand=-__repeatMasking=none  2214    2020    2211    173 195 1NM:i:22    ms:i:258    AS:i:258    nn:i:0  tp:a:P  cm:i:5  s1:i:48 s2:i:74 de:f:0.0895 rl:i:15 cg:Z:61M2D12M1I56M2D17M2D21M3I18M
42b3f838-c198-483a-a822-ba3de68482f0    313 84  273 -   canFam4_refGene_NM_001003060__range=chr7:27649342-27674458__5'pad=0__3'pad=0__strand=-__repeatMasking=none  2751    2201    2393    168 195 0NM:i:27    ms:i:226    AS:i:226    nn:i:0  tp:a:S  cm:i:8  s1:i:74 de:f:0.1204 rl:i:15 cg:Z:62M2D8M1I20M2I38M2D21M2D37M
```
I ran again the following codes: 
```
head vico_R1.fastq.paf > temp.paf
jaffa-2.2-0/tools/bin/process_transcriptome_align_table temp.paf 1000 /groups/dog/aurore/test_JAFFAL/REF_canFam4/canFam4_UU_Cfam_GSD_1.0.tab > temp.txt
```
And I get the same error:
```
Done reading in transcript IDs
Reading the input alignment file, temp.paf
0
terminate called after throwing an instance of ‘std::out_of_range’
  what():  map::at
Aborted (core dumped)
```
Could it be an issue due to the non-supported genome?
Thanks,
Aurore

**Comment by nadiadavidson** [comment]
Hi, I've never had anyone ask about fusion calling in dog before. That's fascinating! Is it for cancer? or to identify structural variants between breeds? or something else?

JAFFAL expects the annotation to be Gencode or Ensembl (ie. a prefix of "EN" to the gene and transcript names). It looks like canFam5 and canFam3 have Ensembl annotations in UCSC Genome Browser, so you could try using one of those.

I will update our documentation to make it clear that Ensembl is needed.

Cheers,
Nadia.

**Comment by Aurore-B** [comment]
Hi Nadia,
Thanks for your quick reply.

My mistake, I didn’t pay attention that the chosen track changed from Ensembl to RefSeq when I selected Dog annotation. I will change my annotation files to reprocess jaffal and let you know if it works.

Indeed, with my colleague @tderrien, we are working on naturally occurring canine cancers and also breed-specific rearrangements. We wanted to test whether we could find common/orthologous fusion genes in dog and human cancers.

Cheers,
Aurore

**Comment by Aurore-B** [comment]
Hi Nadia,
sorry for the delay.

It works well with the Ensembl CanFam3 ! :) thanks again !

Aurore
