### ISSUE TITLE
pacbio pre-processing

### ISSUE THREAD

**Issue by gr8ape** [Oshlack/JAFFA#73]
Hi,
Do you recommend using the pacbio reads that have been polished with CCS or is their benefit to using the raw subreads.bam converted to fastq as input?

**Comment by nadiadavidson** [comment]
Hi,
Great question. If it's easy to try both, I would do that on a few samples to see which gives the better sensitivity. In theory the raw data should be fine and JAFFAL can tolerate quite a high error rate. However, if each subread is treated as an individual read this might inflate the number of reads supporting fusions and you'll likely get a lot of false positives. Results from CCS should be safer, but it's not clear to me how the sensitive would compare to the raw reads. Very happy for you to report back if you test this out!

Cheers,
Nadia.

**Comment by gr8ape** [comment]
@nadiadavidson   thanks for the prompt reply. I'll post back here once I've done some additional R&D and let you know what we found
