### ISSUE TITLE
how to get Pig's known_fusions.txt file

### ISSUE THREAD

**Issue by TianYHYA** [Oshlack/JAFFA#76]
Hi,
First, many thanks for developing this tool and the nice tutorial in the wiki.
I want to detect the pig transcript fusion, but I don't know how to get Pig's known_fusions.txt file.
Can you help me?
Many thanks for your help!

**Comment by nadiadavidson** [comment]
Hi, known_fusions just lists known fusions and adds some extra information into the results table. It isn't really used for detecting fusions you can could either used the human file that's already provided, or try providing an empty file.
Cheers,
Nadia.
