### ISSUE TITLE
Running JAFFA on osx-arm64

### ISSUE THREAD

**Issue by nrhorner** [Oshlack/JAFFA#81]
Hi,

I'm currently using JAFFAL on Linux with no issues. It's not working for me on Mac with an M1 chip. It looks an issue with bpipe, and I have ticketed them, but was wondering if you had any ideas about this.

Cheers,

Neil

**Comment by nadiadavidson** [comment]
Hi Niel,
We haven't tested on any recent macs, but could have a look. What error are you getting? 
Cheers,
Nadia.
