### ISSUE TITLE
hg19_genCode19_blast.nhr

### ISSUE THREAD

**Issue by km-2021** [Oshlack/JAFFA#82]
Hi,

I am running Jaffa with hg19, but by default, the hg19 version of the blast files are not generated (ex. *:blast.nhr, blast.nin, blast.nsq) and fails at the annotation stage. Can you please tell me how to solve this problem?

**Comment by nadiadavidson** [comment]
Hi, please try following the instructions here, https://github.com/Oshlack/JAFFA/wiki/FAQandTroubleshooting#how-can-i-run-jaffa-with-hg19-or-mm10 and let us know if you run into any issues.

Cheers,
Nadia.
