### ISSUE TITLE
Support for plant genomes

### ISSUE THREAD

**Issue by Zhuxitong** [Oshlack/JAFFA#87]
Hi, @nadiadavidson or other developers!

Thanks for making JAFFA available for long sequencing reads, which I believe is very urgent for the identification of fusion transcripts using widely applied long sequening reads. However, fusion genes with long sequencing reads supported has rarely been investigated in plants over animals especially in human. So, I have several questions concerning this.

1, It's noticed that the support of custom genomes has been limited to USCS type as described [here](https://github.com/Oshlack/JAFFA/wiki/FAQandTroubleshooting#how-can-i-generate-the-reference-files-for-a-non-supported-genome). After checking the descriptions, I wonder if JAFFAL could be run on non-UCSC genomes with some modifications, such as adding a prefix "EN" to each genes in the annotaion file?

2, Shall you please provide some suggestions or cautions when applying JAFFAL to plant genomes, such as those caused by difference of repeat content in plants over animals?

**Comment by ada2880** [comment]
Hi @nadiadavidson 
Any idea here please? :)
Alb

**Comment by nadiadavidson** [comment]
Hi,

1. In theory it would be possible to run JAFFAL with plants, but a new reference would need to be generated and the instructions we provide wouldn't be sufficient (as you found out!). The transcript names would need to be in the same format as ENSEMBL (including the 'EN' and you would need to generate the equivalent of the UCSC Table Browser Table (which we give the suffix .tab in the human reference). So it would be quite a bit of work to make, although not impossible.

2. I *think* it should be fairly similar and work okay for plants, but we have never tested this. Plants tend to have a lot of paralogs, so you might find more false positives due to these. But we also have these in humans and JAFFAL does okay with them. The quality of the reference genome and annotation might be a factor in the fusion performance depending on the plant.

It you get it running, we'd love to hear back as we get enquires about fusion finding in plants every so often. If you write up instruction for generating a plant reference for JAFFAL, I'd be more than happy to add this to our wiki page.

Cheers,
Nadia.

**Comment by Zhuxitong** [comment]
Hi, @nadiadavidson !

I am glad to hear your response in great details! Last week, I attempted to modify your code and generated required files. Finally I was able to make JAFFA work for my custom genome. I will post the steps or modifications I made.

To get those reference files, you need at least two files at beginning:

1. genome sequence in FASTA format, like `sp.fa`;
2. annotation file in GTF format, like `sp.gtf`. If you have only gff3, you can convert it into GTF format using gffread command.

Then we need to generate other necessary files. Let's assume the two related parameters fed into JAFFA are `-p genome=sp -p annotation=anno`, which means the prefix for our custom genome will be `sp_anno` (similar to hg38_genCode22).

1. Transcript fasta file.
> gffread sp.gtf -g sp.fa -w sp_anno.fasta

We need reformat the header to ensure only transcript ID is left:
> cat sp_anno.fasta | awk '{if(/^>/){print $1}else{print}}' | $JAFFAL_HOME/tools/bin/reformat fastawrap=0 in=stdin.fa out=stdout.fa > sp_anno.fa

The header of this fa file would like this:

> \>transcriptID
ATCTCTC......

2. Another file we need is .tab:

> gtfToGenePred sp.gtf sp.gpd -genePredExt

Reformat sp.gpd:

>  awk '{print "1\t"$0}' sp.gpd | csvtk -tH add-header -n '#bin,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,exonCount,exonStarts,exonEnds,score,name2,cdsStartStat,cdsEndStat,exonFrames' > sp_anno.tab

3. Finally the Masked file:

> cat sp.gtf | grep -P "\texon\t" | awk '{print $1"\t"$4-1"\t"$5"\t"$10"\t.\t"$7}' | sortBed > sp_anno.bed
bedtools maskfasta -fi sp.fa -fo Masked_sp.fa -bed sp_anno.bed

All other files, including `bowtie and blast index`, and an ampty `known_fusions.txt` can be generated according to [how-can-i-generate-the-reference-files-for-a-non-supported-genome](https://github.com/Oshlack/JAFFA/wiki/FAQandTroubleshooting#how-can-i-generate-the-reference-files-for-a-non-supported-genome) using above files.

Next, I modified the regular pattern in `src/process_transcriptome_align_table.c++`:

> if(regex_search(trans_id,m,regex`("_(EN[^_]*)__")`)){ //Assumed ENSEMBL annotation naming here
to
if(regex_search(trans_id,m,regex`(">(.*)$")`)){ //Assumed ID only here

After this modification, we need to delete the previous `process_transcriptome_align_table command under tools/bin/ ` and re-compile the install script. Simply run:

> /path/to/JAFFA/install_linux64.sh

Then the below command worked for me (Asuming we have put the database files under JAFFA home directory):

> $JAFFAL_HOME/tools/bin/bpipe run -n 1 -p genome=sp -p annotation=anno $JAFFAL_HOME/JAFFAL.groovy trans_test.fasta

We could also generate a test file which contains some artificial fusion transcripts to verfiy if JAFFA works correctly.

> Download a [script](https://github.com/FusionSimulatorToolkit/FusionSimulatorToolkit/wiki) that could make artificial fusion transcripts from GFF and genome FASTA file:
~/path/to/FusionSimulatorToolkit-master/FusionTranscriptSimulator sp.gff sp.fa 20 > chims.fasta

Then run `JAFFAL `or `JAFFA_direct `(I only test these two because I am using long sequencing reads):

> $JAFFAL_HOME/tools/bin/bpipe run -n 1 -p genome=sp -p annotation=anno $JAFFAL_HOME/JAFFAL.groovy chims.fasta

If we can identify those fusion transcript using JAFFA without any errors, I think we have successfully applied JAFFA to our custom genome.


I am now processing my own data and found an interesting problems related to [Issue73](https://github.com/Oshlack/JAFFA/issues/73). I don't have raw subreads or CCS sequences but only the final high-quality transcripts obtained from CCS. Then I could only detect several `PotentialTransSplicing `and lots of `NoSupport`. Since each high-quality transcript was supported by at least three CCS sequences, can we say if we use CCS sequences, those `PotentialTransSplicing` would turn into `HighConfidence` and `NoSupport` into `LowConfidence`? Do you recommand using those high-quality transcript as input? This seems to be related with the definition of `reads` and it will be different if we use different data type as input. And I think it will also be great helpful if you could post the pre-process code used in your _Genome biology_ paper for direct sequencing and pacbio data.

Again, thanks for developing JAFFA, it's really helpful :)

**Comment by nadiadavidson** [comment]
Hi,

Thank you that it excellent. Just to confirm are you happy for me to add these instructions to our wiki or provide a link to this thread for those that are analysing plants?

PotentialTransSplicing events can certainly be true fusions and this can happen is the amount of data given to JAFFAL is low as it sounds like is the case for you. The read support is really a proxy for the number of molecule where the fusion was seen. So if the high-quality transcripts come from one molecule sequenced multiple times (subreads), then the read support would still be 1 and the classification lower. The only way to know if the PotentialTransSplicing events are true fusions is will orthogonal data and experimental validation. The "NoSupport" fusions have 0 reads support, so these are likely to be false positives even with low depth data. There is a intermediate file created by JAFFA ending in .txt that lists all fusion candidates it finds early on in the pipeline. Many of these get filtered out, but it is a good place to look for extra supporting reads, as sometime true fusion reads get filtered out.

In our Genome Biology paper we didn't do any particular preprocessing of the data. We downloaded from the listed source and then ran JAFFAL. The original publications and/or databases that house the data should describe how they pre-processed it.

All the best,
Nadia.

**Comment by Zhuxitong** [comment]
@nadiadavidson hi,

Sure, I am happy if this could help others:)

And for pacbio data pre-process, I am now planing to use full-length non-chimeric (better known as FLNC) as input since FLNC reads are complete but not being culstered into high-quality sequences, so it may provide more information. We are also going to do some experimental validations based on the output of JAFFA.

Again, thanks for your kindly response. I think this Issue could be closed now :)
