### ISSUE TITLE
stage report_3_gene_fusions failed

### ISSUE THREAD

**Issue by sophielemoine** [Oshlack/JAFFA#90]
Dear JAFFA developper, 
I managed to make a docker image for JAFFA version 2.3 that is nearly working for me.
One of the last step (that comes after the final stage, what is strange), make_3_gene_fusion_table - has an issue and is not working. 

Here is what happens :

bash: line 1: 2022126/2022126.summary: Permission denied
Cleaned up file 2022126/2022126.3gene_summary to .bpipe/trash/2022126.3gene_summary.3
ERROR: stage report_3_gene_fusions failed: Command 155 in stage report_3_gene_fusions failed with exit status = 126 : 
$make_3_gene_fusion_table 2022126/2022126.summary 2022126/2022126.txt 2022126/2022126.3gene_reads > 2022126/2022126.3gene_summary 

2022126/2022126.summary exists and has no special rights that prevent its access. 
Can you help me with this ??
Thanks a lot.

**Comment by nadiadavidson** [comment]
Hi Sophie,
Does it work okay outside of Docker? e.g. in a regular linux environment? Do you get the same error on other datasets?

This part of the pipeline is at the very end. It's looking for three gene fusions amongst the already called breakpoints in the .summary file. These are quite rare, so if you aren't interested in phasing breakpoints (or are happy to so this manually), you could ignore the error and still use the .summary file with all the fusion calls.

Cheers,
Nadia.

**Comment by sophielemoine** [comment]
Dear Nadia, 
I didn't have the opportunity to test JAFFA outside my docker file because I do not want to enter package version conflits on my lab servers. The error occurs whatever the dataset is. It's probably due docker...
If it's OK to use the summary file, that's what I will do.
Thanks for your comments and advice !
Sophie.

**Comment by nadiadavidson** [comment]
Happy to help.
You can quite safely install JAFFA's dependencies without conflicts on the lab servers. All the required software is installed into a tool subdirectory and linked with a config file (so no changes to your paths will occur). This might be easier to run than Docker.

All the best,
Nadia.
