### ISSUE TITLE
run with error

### ISSUE THREAD

**Issue by asaki1986** [Oshlack/JAFFA#92]
Hi,

`JAFFA-version-2.3/tools/bin/bpipe run -p genome=hg19 -p annotation=genCode19 -p fastqInputFormat="%_raw_*.fq.gz" JAFFA-version-2.3/JAFFA_direct.groovy /data/NGS/test/*.fq.gz`

I used the command above to analyze the test RNA data.
Command log showed that the Stage get_unmapped was finished with duration 5 mins.
But encountered a ERROR: Command failed with exit status = 1 :
ignorebadquality=t in=jaffa/test/unmapped.fastq out=jaffa/test/temp.fasta threads=16 ; sort=d in=jaffa/test/temp.fasta out=test/test.fasta threads=16 absorbcontainment=f; rm jaffa/test/temp.fasta jaffa/test/unmapped.fastq 2> /dev/null

It will be of great help if you can help.

Best,
Junfeng

**Comment by nadiadavidson** [comment]
Hi Junfeng,

Could you please answer the questions listed here, https://github.com/Oshlack/JAFFA/wiki/FAQandTroubleshooting#other-errors   
to help us assess what's gone wrong.

Cheers,
Nadia.

**Comment by asaki1986** [comment]
> Hi Junfeng,
> 
> Could you please answer the questions listed here, https://github.com/Oshlack/JAFFA/wiki/FAQandTroubleshooting#other-errors to help us assess what's gone wrong.
> 
> Cheers, Nadia.

Hi Nadia,

The same error occurred when I test the demo data in the wiki page.
I installed the packages following the instructions.

I also test the installation in my Mac, but failed to execute the binary files for bowtie.

Any other instructions that I can perform to fix the error?

Best,
Junfeng

**Comment by asaki1986** [comment]
I re-installed the tools, and now it works fine!

Thanks
