### ISSUE TITLE
Support for T2T-CHM13?

### ISSUE THREAD

**Issue by majdabdul** [Oshlack/JAFFA#96]
Hi,

Thanks for creating this tool! I'm using the T2T-CHM13 human genome. Is there a way I can use it with JAFFA?

Thanks again,
Majd

**Comment by nadiadavidson** [comment]
Hi Majd,

We haven't build reference files to support T2T yet, but you could try to build your own if needed, https://github.com/Oshlack/JAFFA/wiki/FAQandTroubleshooting#how-can-i-generate-the-reference-files-for-a-non-supported-genome 

Cheers,
Nadia.
